@startuml
actor Socio
actor Bibliotecario

Socio -- (Reserva Libros)
Socio -- (Prestar libro)
Socio -- (Devolver Libro)

Bibliotecario -- (Prestar libro)
Bibliotecario -- (Actualizar Actálogo)


@enduml